name: Daily Predictions Update

# Trigger every day at 08:00 UTC
on:
  schedule:
    - cron: '0 8 * * *'  # daily at 08:00 UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  daily-predictions:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # We'll use PAT explicitly for push

    # 2. Setup Python 3.10
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pandas yfinance requests pyyaml

    # 4. Run headless prediction script
    - name: Run daily predictions
      run: python predict_headless.py

    # 5. Commit & push predictions using GH_PAT
    - name: Commit & push predictions
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add predictions_log.csv
        git commit -m "Daily predictions update" || echo "No changes to commit"
        git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:main
