name: Daily Predictions Update

# Trigger every day at 00:00 UTC
on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  daily-predictions:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Python 3.10
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pyyaml yfinance requests

    # 4. Run headless prediction
    - name: Run predictions
      run: |
        python predict_headless.py

    # 5. Commit and push predictions
    - name: Commit and push predictions
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add predictions_log.csv
        git commit -m "Daily predictions update" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
