name: Hourly Predictions Update

on:
  schedule:
    - cron: '0 * * * *'  # every hour at minute 0
  workflow_dispatch:      # allows manual trigger

jobs:
  hourly-predictions:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Use PAT explicitly for push

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pandas yfinance requests pyyaml plotly textblob pytrends scikit-learn

      # 4. Ensure data folder & CSV files exist
      - name: Create data folder and CSV files if missing
        run: |
          mkdir -p data
          touch data/actual_data.csv
          touch data/predictions_log.csv
          touch data/ai_predictions_log.csv

      # 5. Update market indicators dynamically
      - name: Update market indicators
        run: python update_weights.py

      # 6. Fetch actual data
      - name: Fetch actual data
        run: python fetch_data.py

      # 7. Generate predictions
      - name: Run headless prediction script
        run: python predict_headless.py

      # 8. Generate AI predictions and backtest (ensures ai_predictions_log.csv is filled)
      - name: Generate AI predictions & backtest
        run: |
          python -c "from ai_predictor import predict_next_n, backtest_ai; predict_next_n(None, None, 'Gold'); predict_next_n(None, None, 'Bitcoin'); backtest_ai('Gold'); backtest_ai('Bitcoin')"

      # 9. Commit & push CSV updates safely
      - name: Commit & push CSV updates
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

          git add data/predictions_log.csv data/actual_data.csv data/ai_predictions_log.csv weight.yaml
          git commit -m "Hourly update" || echo "No changes to commit"

          # Pull with "theirs" strategy to prefer workflow changes in conflicts
          git pull --rebase -X theirs https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD || true

          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:main
