name: Hourly Predictions Update

# Trigger every hour
on:
  schedule:
    - cron: '0 * * * *'  # every hour at minute 0
  workflow_dispatch:      # allows manual trigger

jobs:
  hourly-predictions:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # We'll use PAT explicitly for push

    # 2. Setup Python 3.10
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Ensure data folder exists
    - name: Ensure data folder exists
      run: mkdir -p data

    # 5. Run fetch_data.py to get actual prices
    - name: Fetch actual data
      run: python fetch_data.py

    # 6. Run predict_headless.py to calculate predictions
    - name: Run predictions
      run: python predict_headless.py

    # 7. Commit & push updates using GH_PAT
    - name: Commit & push CSV updates
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add data/predictions_log.csv data/actual_data.csv
        git commit -m "Hourly update" || echo "No changes to commit"
        git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} HEAD:main
